### ISSUE TITLE
Add data to a collection

### ISSUE THREAD

**Issue by heikokrebs** [AdditionApps/flexible-presenter#11]
Hello,

first of all: great package! Thanks a lot for all the hard work!

i came a across a problem i couldn't solve yet: i need to add some data to a collection.
The `with()` method adds/transforms data in every item - but i need to add some data to the collection itself.

Is there any way or what would you suggest?

Thanks a lot!

**Comment by fourstacks** [comment]
Hi @heikokrebs - my initial thought is that this is probably not currently possible but I'm also not sure I get what it is that you're trying to achieve.  Could you give me a code example of what you'd want to see as output?

**Comment by heikokrebs** [comment]
Hey @fourstacks, thanks for the fast reply!
I have a collection of some items and also want to pass an url to my frontend, where to create a new item. So the data that my frontend needs is something like this

```
[
  'data' => [ …],
  'meta' => [ …],
  'links' => [
    …
    'create' => 'https//someurl.com'
  ]
]
```

The overall structure of this response is defined by a modified `LengthAwarePaginator` (I am using InertiaJS).
At the moment i am doing something like this in my controller:

```
   return Inertia::render('Items/Index', [
            'filters' => $request->all(['search', 'trashed']),
            'items' => collect(ItemPresenter::collection($urls))->mergeRecursive([
                'links' => [
                    'create' => action([__CLASS__, 'create']),
                ]
            ]),
        ]);
```

**Comment by fourstacks** [comment]
OK, if I've understood things correctly, you want the presenter to spit out a paginated list of presented resources but the top level of the output should be in the format in your first code sample?

If that's correct you might be able to achieve what you're after with a custom paginator instance.  Flexible Presenter can already accept a paginator instance and will [spit out results like this](https://github.com/AdditionApps/flexible-presenter#postpresentercollectionposts).

However, as well as accepting vanilla paginator instances it'll also accept a custom one too so perhaps you could investigate using a custom pagnation class that overrides to `toArray` method to produce the results you want.

That said I don't know if that will really be less verbose than your current solution.

In an ideal world, would you want an API that looks a bit like this?

```
items' => ItemPresenter::collection(Item::paginate())
    ->append('links', [
        'create' => action([__CLASS__, 'create']),
    ]),
```

The `appends` method would add the key specified in argument one along with the value specified in argument two.

Whilst I don't have a use for this myself at the moment I can see the value in this so I'll try and make some time to dig into it (assuming the above solution looks like the right approach for your problem)

**Comment by heikokrebs** [comment]
Hey @fourstacks!

Yes i already have a custom paginator with an `toArray()` method that formats the data to something like:

```php
[
  'data' => […],
  'meta' => […],
  'links' => […]
]
```

But in this case i want to add something to this structure - like another element to the `links` array before i pass it to the view/return it. So something like your proposed `append()` seems right! But it would have to recursively merge the data - like in my example above.

Again: thanks for your fast and nice reply!

**Comment by fourstacks** [comment]
Hi @heikokrebs.  I'm planning on making some updates to the package this week and pushing out a v2 which will hopefully include support for custom values as above (if I don't hit too many roadblocks).

Can I just confirm what you mean when you say you'd want to see the data recursively merged?  I'm not sure I quite get what you mean by that in this context.  Could you give me an example of what you'd want to see as the package API for adding a custom property and also what you'd be expecting to see as the output? 

I get that you'd maybe want to add a `links` property to the outermost layer of the initially presented resource but I don't quite understand why (or indeed) where you'd recurse that `links` property into?

**Comment by heikokrebs** [comment]
Hey @fourstacks 
The best example i think is some paginated data. I have a custom `LengthAwarePaginator` with an `toArray` method that returns an structure as mentioned above:

```php
[
  'data' => […],
  'meta' => […],
  'links' => [
     'prev_page_url' => $this->previousPageUrl(),
     'next_page_url' => $this->nextPageUrl(),
     'elements' => $this->links(),
   ]
]
``` 

So there are already some links in the corresponding array. But now for example i also want to return a link to the Create form to the frontend. So i need to add a new element to the `links` array without overwriting the already existing elements. This is where i use `mergeRecursive`:

```php
return Inertia::render('Items/Index', [
  'filters' => $request->all(['search', 'trashed']),
  'items' => collect(ItemPresenter::collection($items))->mergeRecursive([
    'links' => [
      'create' => action([__CLASS__, 'create']),
    ]
  ]),
]);
```

So the Frontend gets something like:

```php
'filters' => […]
'items' =>  [
  'data' => […],
  'meta' => […],
  'links' => [
     'prev_page_url' => '…',
     'next_page_url' => '…',
     'elements' => '…',
     'create' => '…',
   ]
]
```

An Package-API as you proposed above seems fine to me:

```php
return Inertia::render('Items/Index', [
  'filters' => $request->all(['search', 'trashed']),
  'items' => ItemPresenter::collection(Item::paginate())
    ->append('links', [
        'create' => action([__CLASS__, 'create']),
    ]),
]);
```

**Comment by fourstacks** [comment]
Ah, gotcha.  Understand now, thanks!  OK, will hopefully ship this sometime this week 👍

**Comment by fourstacks** [comment]
@heikokrebs - Got to this a little sooner than expected!  Version 2.0.0 supports appending any number of additional key/value pairs: https://github.com/AdditionApps/flexible-presenter#appends

**Comment by heikokrebs** [comment]
@fourstacks That looks great, thanks a lot!
