### ISSUE TITLE
lazy() does not work as intended

### ISSUE THREAD

**Issue by heikokrebs** [AdditionApps/flexible-presenter#12]
Hello,

i stumbled across a problem with `lazy()`. When i have a field defined with the `lazy()` function it IS evaluated twice when i pass the presenter to Inertia for example - even when i exclude the corresponding field.
If i use the closure directly it works as intended.

**Example:**

```php
class TestPresenter extends FlexiblePresenter
{
    public function values(): array
    {
        return [
            'id' => 1,
            'lazy' => $this->lazy(
               dump('lazy')
            ),
            'closure' => function() {
                return dump('closure');
            },
        ];
    }
}
```

And in the controller something like:

```php
return TestPresenter::make([1,2,3,4])->only('id');
```

The closure will not be evaluated - but the `lazy()` will be evaluated twice. Once in the `validateKeys()` function and again when in the `get()` function.

**Comment by fourstacks** [comment]
Ah damn - yeah I've been able to replicate this myself now.  Weird as I had a test covering the lazy method but I guess it wasn't testing for the right things.  Thanks for the heads up.

Will have to see if I can come up with a new way of tackling lazy evaluation...

**Comment by fourstacks** [comment]
OK, so the `lazy` method is now removed in v2.0.0.  From now on it's just regular closures or if you're using php 7.4 you can of course use short closures which look pretty good IMO!

```
[
    'foo' => fn()  => $this->comments()->count()
]
```

**Comment by heikokrebs** [comment]
@fourstacks Thanks a lot!
