### ISSUE TITLE
Access pivot data using nested presenter

### ISSUE THREAD

**Issue by Silver343** [AdditionApps/flexible-presenter#18]
Hi,

is it possilbe to access the pivot data whilst using a nested presenter?

Thanks

**Comment by fourstacks** [comment]
Hi @Silver343  - what have you tried so far?  

You should certainly be able to access data from a pivot table via a related model in a nested presenter.  For example let's assume you have a many to many relationship between a `Post` and `Image` model and a pivot table with an extra column called `test`.

If you have your relationship methods set up correctly (remembering to use the `withPivot` method to define the extra pivot fields you want to access) then in your presenter class you should just be able to call `$this->pivot->test` to retrieve that value.

There's now a [test showing access of pivot data](https://github.com/AdditionApps/flexible-presenter/blob/262e65ac18824462a68f7576da74f7c3623a7751/tests/FlexiblePresenterTest.php#L474) if you want a full example

**Comment by Silver343** [comment]
Hi @fourstacks ,

Thanks for the help, I had the relationship stuff all correct just couldn't get the syntax for the presenter, wasn't using with(), I wasn't able to get it to work whilst using whenLoaded() in the preset, but using 

` public function presetFacilityRelation()
    {
        return $this->with(function () {
            return [
                'facilities' => FacilityPresenter::collection($this->facilities),
            ];
        });
    }` 


did the trick. The example presenters in the tests are a great help, ill be sure to use them in the future.

Thanks
