### ISSUE TITLE
Remove Presenter's `all` method

### ISSUE THREAD

**Issue by ycs77** [AdditionApps/flexible-presenter#23]
1. I was just thinking that if you don’t use `only` or `except`, the `all` method is the same as `get`.
2. I occasionally get confused because Laravel Collection uses `all` return array, but Presenter uses `get`.

So I think can actually remove `all` method.

Any other ideas? 😕

**Comment by fourstacks** [comment]
Yep you're right I guess that it's a little inconsistent if you compare it to Laravel Collections though that wan't really top of my mind when designing the API as they are two fairly different tools.  I do agree that `all` is unlikely to see much usage out in the wild but as it's part of the public API now, removing it would be a breaking change and I'm not really sure that it's removal is worth the major version bump?

What we could perhaps do is remove it's documentation from the readme?

**Comment by fourstacks** [comment]
On a second read through I think I might keep the `all` method in the docs.  I've added a little explanation as part of #20 to try and make it clear what the difference and similarities are with `get`.  I think `all` has its place as its possible people might use the package in non-inertia settings where the `arrayable` feature won't kick in.  In those situations it's a little clearer (to me at least) that `all` will get all the presenters keys - `get` is a little more ambiguous I think.

If we get more feedback along the same lines as yours though I'm open to removing it from the docs or from the package wholesale in a future major version.

**Comment by ycs77** [comment]
The `all()` method part from documentation is easy to understand. Great!
