### ISSUE TITLE
Chain only() and except()

### ISSUE THREAD

**Issue by ycs77** [AdditionApps/flexible-presenter#30]
Use chain only() and except() has two options:

### 1. addOnly()

* only(): force set only keys
* addOnly(): add only keys

except() same.

PR: #31

### 2. forceOnly()

* only(): add only keys
* forceOnly(): force set only keys

except() same.

PR: #32

---

@fourstacks What do you think?

**Comment by fourstacks** [comment]
Hey @ycs77 - thanks for the PRs.

I've looked over both and whilst I kinda get what's happening, I can't really work out the use case for these new methods?  I'm also a little uncertain as to whether two two PRs are two different suggestions for tackling some problem or whether you're suggesting them both for inclusion?

Perhaps you could give me a few examples of how they would be used and what problems they help to overcome?  It might be that there's a legitimate use case here that I'm not seeing.  Thanks

**Comment by ycs77** [comment]
The example has UserPresenter and different only() usage:

```php
class UserPresenter extends FlexiblePresenter
{
    public function values(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'description' => $this->description,
            'avatar' => $this->avatar,
        ];
    }
}
```

### 1. addOnly()

Force set only() (`only()`) in `presetProfile()`, and add only (`addOnly`) `postsCount`, `likesCount`:

```php
public function presetProfile()
{
    return $this->only('name', 'avatar');
}

public function index(User $user)
{
    $user->loadCount('posts', 'likePosts');

    return Inertia::render('User/Profile', [
        'user' => UserPresenter::make($user)
            ->preset('profile')
            ->addOnly('postsCount', 'likesCount')
            ->with(function (User $user) {
                return [
                    'postsCount' => $user->published_posts_count,
                    'likesCount' => $user->like_posts_count,
                ];
            })
            ->get(),
    ]);
}
```

### 2. forceOnly()

Force set only() (`forceOnly()`) in `presetProfile()`, and add only (`only`) `postsCount`, `likesCount`:

```php
public function presetProfile()
{
    return $this->forceOnly('name', 'avatar');
}

public function index(User $user)
{
    $user->loadCount('posts', 'likePosts');

    return Inertia::render('User/Profile', [
        'user' => UserPresenter::make($user)
            ->preset('profile')
            ->only('postsCount', 'likesCount')
            ->with(function (User $user) {
                return [
                    'postsCount' => $user->published_posts_count,
                    'likesCount' => $user->like_posts_count,
                ];
            })
            ->get(),
    ]);
}
```

---

After finishing the above example, I seem to think that `forceOnly()` is not needed anymore, just a simple chain only feature.

### 3. Only use chain only()

```php
public function presetProfile()
{
    return $this->only('name', 'avatar');
}

public function index(User $user)
{
    $user->loadCount('posts', 'likePosts');

    return Inertia::render('User/Profile', [
        'user' => UserPresenter::make($user)
            ->preset('profile')
            ->only('postsCount', 'likesCount')
            ->with(function (User $user) {
                return [
                    'postsCount' => $user->published_posts_count,
                    'likesCount' => $user->like_posts_count,
                ];
            })
            ->get(),
    ]);
}
```

**Comment by fourstacks** [comment]
Hey @ycs77 - thanks for the examples.  Sorry to be a bit slow here but I'm still not entirely clear what problem these new methods are trying to solve?  What is is that you want to do that you're unable to do with the current set of api methods?

**Comment by ycs77** [comment]
The problem I want to solve is that `only()` is defined in `preset`, but I want after chaining other `only()` keys.
