### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by marbuser** [AdditionApps/flexible-presenter#4]
Hey there,

Just wondering how you would go about using pagination with this? I'm currently using an API Resource for mapping properties and then an API Resource Collection for grouping them if I need to include links and pagination info.

How would I provide this same information with `flexible-presenter` or is it even possible currently?

Thanks!

**Comment by fourstacks** [comment]
Hi @marbuser - thanks for the suggestion!  My own use case (that led me to build this package) doesn't currently require pagination and as I was a bit pushed for time I left it out for now.  However I can see pagination support being very useful.  

I've got quite a bit on at the moment so I can't promise a quick solution to this but I'm always open to accepting PRs if you end up tackling it yourself.  Will close this for now but I'll make sure I give it some thought when I get a little spare time.

**Comment by fourstacks** [comment]
Pagination support is now available in v1.3.0 thanks to @ycs77
